[package]
name = "ojas-train"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tracing = { workspace = true }
ojas-core = { path = "../ojas-core" }
ojas-metal = { path = "../ojas-metal" }
ojas-formats = { path = "../ojas-formats" }
anyhow = "1"
half = "2"
metal = "0.32"
objc = "0.2"
serde_json = "1"

[dev-dependencies]
