//! CUDA kernel families, split by function to mirror ojas-metal/src/kernels/.
//! Entry names are Metal-canonical wherever a counterpart op exists.
//!
//! Families here: ops / gemv / gemv_iq / gemv_q8 / moe / moe_iq / attn_core / attn / ssm / cnn /
//! learn (training) / bert (the text encoder). Metal-only families (mla) have no CUDA dialect yet — `family_source`
//! returns None.
//!
//! `gemv_iq` is split out for the reason Metal splits `requant_iq`: the IQ codebooks are ~41 KB
//! of constant memory that only those decoders index.
pub mod attn;
pub mod attn_bidir;
pub mod attn_core;
pub mod bert;
pub mod cnn;
pub mod gemm_f16;
pub mod gemm_q;
pub mod gemv;
pub mod gemv_q8;
pub mod learn;
pub mod moe;
pub mod moe_iq;
pub mod nat;
pub mod ops;
pub mod prelude;
pub mod qwen35;
pub mod rope_m;
pub mod ssm;
pub mod vision;

use std::collections::HashMap;
use std::sync::OnceLock;

/// (family, kernel bodies). Every family compiles against the shared PRELUDE.
const SPLIT: &[(&str, &str, &[&str])] = &[
    ("ops", ops::BODY, ops::NAMES),
    ("gemv", gemv::BODY, gemv::NAMES),
    ("gemv_q8", gemv_q8::BODY, gemv_q8::NAMES),
    ("gemm_f16", gemm_f16::BODY, gemm_f16::NAMES),
    ("gemm_q", gemm_q::BODY, gemm_q::NAMES),
    // body-less: every entry is generated by `nat::instantiate(grid_formats)`
    ("gemv_iq", "", &[]),
    ("attn_core", attn_core::BODY, attn_core::NAMES),
    ("attn", attn::BODY, attn::NAMES),
    ("attn_bidir", attn_bidir::BODY, attn_bidir::NAMES),
    ("ssm", ssm::BODY, ssm::NAMES),
    ("cnn", cnn::BODY, cnn::NAMES),
    ("learn", learn::BODY, learn::NAMES),
    ("moe", moe::BODY, moe::NAMES),
    ("moe_iq", moe_iq::BODY, moe_iq::NAMES),
    ("rope_m", rope_m::BODY, rope_m::NAMES),
    ("vision", vision::BODY, vision::NAMES),
    ("bert", bert::BODY, bert::NAMES),
    ("qwen35", qwen35::BODY, qwen35::NAMES),
];

/// Reference-repo kernels deliberately not ported (ablation series, diagnostics, superseded
/// bring-up paths). Guarded by a test so they do not reappear.
pub const RETIRED: &[&str] = &[
    "gemm_q4_s8_mma", "gemm_q4_s8_mma2", "gemm_q4_s8_mma3", "gemm_q4_s8_mma4",
    "gemm_q4_s8_mma5", "gemm_q4_s8_mma6", "gemm_q4_s8_mma7", "gemm_q4_s8_mma8",
    "gemm_q4_s8_mma9", "gemm_q4_s8_mma10", "gemm_q4_s8_mma11", "gemm_q4_s8_mma12",
    "gemm_q4_s8_mma13", "gemm_q4_s8_mma14", "gemm_q4_s8_mma15", "gemm_q4_s8_mma16",
    "gemm_q4_s8_mma17",
    "gemm_probe_f16", "gemm_probe_mma19", "gemm_probe_mma", "gemm_probe_bare",
    "gemm_s8_bigk", "gemm_s8_plain", "gemm_s8_3stage",
    "attention_flash", "attention_flash_tc2_g", "attention_flash_tc3_g",
];

fn table() -> &'static HashMap<&'static str, &'static str> {
    static T: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();
    T.get_or_init(|| {
        let mut m = HashMap::new();
        for (f, body, _) in SPLIT {
            // Same split as Metal: the decoders are macro text and go everywhere, but the
            // native matvec entry points are instantiated only in `gemv`, so a name resolves
            // to exactly one family.
            let nat_entries = match *f {
                "gemv" => nat::instantiate(nat::plain_formats()),
                // the IQ formats live in their own family so the ~41 KB of codebooks are not
                // compiled into every other one; see `nat::cuda_grids`
                "gemv_iq" => format!("{}\n{}", nat::cuda_grids(),
                                     nat::instantiate(nat::grid_formats())),
                _ => String::new(),
            };
            // cnn is written once and expanded per precision (f32 / f16).
            let body = if *f == "cnn" { cnn::expand(body) } else { body.to_string() };
            // the Q8 family carries its own row-dot/activation helpers
            let body = if *f == "gemv_q8" { format!("{}\n{body}", gemv_q8::HELPERS) } else { body };
            // moe_iq indexes IQ codebooks directly (IQ3_S experts); only the two it reads, for
            // the same constant-memory reason `gemv_iq` exists
            let body = if *f == "moe_iq" {
                format!("{}\n{body}",
                        ojas_core::iq_grids::grids(ojas_core::iq_grids::Dialect::Cuda,
                                                   &["iq3s_grid", "kmask_iq2xs"]))
            } else { body };
            let src: &'static str =
                Box::leak(format!("{}\n{}\n{}\n{}", prelude::PRELUDE, nat::cuda_decoders(), body,
                                  nat_entries).into_boxed_str());
            m.insert(*f, src);
        }
        m
    })
}

pub fn family_source(family: &str) -> Option<&'static str> {
    table().get(family).copied()
}

pub fn families() -> impl Iterator<Item = (&'static str, &'static str)> {
    table().iter().map(|(f, s)| (*f, *s))
}

/// Family that registers a canonical entry name.
pub fn family_of(entry: &str) -> Option<&'static str> {
    if entry.starts_with("gemv_nat_") && nat::names().iter().any(|n| n == entry) {
        // a native matvec lives with its decoder's codebook requirement, not with the others:
        // the grid formats are instantiated into `gemv_iq` so only that family carries the
        // ~41 KB of IQ tables
        let iq = nat::grid_formats()
            .any(|f| entry.strip_prefix("gemv_nat_")
                          .is_some_and(|r| r == f.tag || r.starts_with(&format!("{}_", f.tag))));
        return Some(if iq { "gemv_iq" } else { "gemv" });
    }
    SPLIT.iter().find(|(_, _, names)| names.contains(&entry)).map(|(f, _, _)| *f)
}

/// Resolve a canonical entry name to the compiled-family source holding it.
pub fn source_of(entry: &str) -> Option<&'static str> {
    family_of(entry).and_then(family_source)
}

/// The generated native-quant entry names, leaked once so they join the static namespace. They
/// are generated rather than listed because the format table is shared with Metal; a second
/// hand-written list would drift from it.
fn nat_names_static() -> &'static [&'static str] {
    static N: OnceLock<Vec<&'static str>> = OnceLock::new();
    N.get_or_init(|| nat::names().into_iter().map(|s| &*Box::leak(s.into_boxed_str())).collect())
}

/// All canonical entry names this backend claims.
pub fn all_names() -> impl Iterator<Item = &'static str> {
    SPLIT.iter()
        .flat_map(|(_, _, names)| names.iter().copied())
        .chain(nat_names_static().iter().copied())
}
