#!/usr/bin/env python3
"""Reproduce IQ codebooks from a supplied ggml-common.h; no network access.
Usage: python3 scripts/gen_iq_tables.py reference/llama.cpp/ggml/src/ggml-common.h [--check]
"""
import argparse
import re
from pathlib import Path
p = argparse.ArgumentParser(description=__doc__)
p.add_argument('source', type=Path)
p.add_argument('--check', action='store_true')
a = p.parse_args()
source = a.source.read_text()
target = Path(__file__).resolve().parents[1] / 'crates/ojas-core/src/iq_tables.rs'
names = [('kmask_iq2xs','u8',8),('ksigns_iq2xs','u8',128),('iq2xxs_grid','u64',256),('iq2xs_grid','u64',512),('iq2s_grid','u64',1024),('iq3xxs_grid','u32',256),('iq3s_grid','u32',512),('iq1s_grid','u64',2048),('iq1s_grid_gpu','u32',2048),('kvalues_iq4nl','i8',16)]
values = {}
for name, ty, count in names:
    match = re.search(r'GGML_TABLE_BEGIN\([^,]+,\s*'+name+r'\s*,[^)]+\)(.*?)GGML_TABLE_END\(\)', source, re.S)
    if not match: raise SystemExit(f'missing source table: {name}')
    body = re.sub(r'//[^\n]*|/\*.*?\*/', '', match[1], flags=re.S)
    nums = re.findall(r'-?0x[0-9a-fA-F]+|-?\d+', body)
    if len(nums) != count: raise SystemExit(f'{name}: expected {count}, found {len(nums)}')
    values[name] = nums
if a.check:
    current = target.read_text()
    for name, ty, count in names:
        match = re.search(r'pub const '+name.upper()+r':[^=]+=\s*\[(.*?)\];',current,re.S)
        nums = re.findall(r'-?0x[0-9a-fA-F]+|-?\d+',match[1]) if match else []
        if [int(x,0) for x in nums] != [int(x,0) for x in values[name]]: raise SystemExit(f'table mismatch: {name}')
    print('all 10 IQ codebooks match source exactly')
else:
    text = '// @generated by scripts/gen_iq_tables.py; see third_party/README.md for provenance.\n// DO NOT EDIT BY HAND.\n#![allow(clippy::unreadable_literal)]\n\n'
    for name,ty,count in names:
        text += f'pub const {name.upper()}: [{ty}; {count}] = [\n'
        nums = values[name]
        for i in range(0,len(nums),8): text += '    '+', '.join(nums[i:i+8])+',\n'
        text += '];\n\n'
    target.write_text(text)
